import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import { Oswald, Inter } from "next/font/google";
import "./globals.css";
import Navber from "@/components/navber/Navber";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const oswald = Oswald({
  variable:"--font-oswald",
  subsets:["latin"],
})

const inter = Inter({
  variable:"--font-inter",
  subsets:["latin"],
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${oswald.variable} h-full antialiased`}
      data-theme="light"
    >
      <body className="min-h-full flex flex-col">
        <Navber/>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
